spring:
  application:
    name: reporting_api_gateway
  cloud:
    gateway:
      routes:
        - id: order-details-service-route
          uri: lb://reportingManagement
          predicates:
            - Path=/orderDetails/**

        - id: order-items-service-route
          uri: lb://reportingManagement
          predicates:
            - Path=/report/order-items/**
server:
  port: 8087
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    prefer-ip-address: true
