spring:
  application:
    name: order_api_gateway
  cloud:
    gateway:
      routes:
        - id: order-service-route
          uri: lb://OrderManagement
          predicates:
            - Path=/order/**
        - id: cart-service-route
          uri: lb://OrderManagement
          predicates:
            - Path=/cart/**

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    prefer-ip-address: true
